apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bolao
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bolao
    spec:
      containers:
      - name: bolao-app
        image: marlonramon/bolao
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://admin:${jhipster.registry.password}@jhipster-registry.default.svc.cluster.local:8761/config
        - name: JHIPSTER_REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: registry-secret
              key: registry-admin-password
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://admin:${jhipster.registry.password}@jhipster-registry.default.svc.cluster.local:8761/eureka/
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://bolao-mysql.default.svc.cluster.local:3306/bolao?useUnicode=true&characterEncoding=utf8&useSSL=false
        - name: JAVA_OPTS
          value: " -Xmx256m -Xms256m"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - name: web
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /management/health
            port: web
        livenessProbe:
          httpGet:
            path: /management/health
            port: web
          initialDelaySeconds: 180

